### PR TITLE
Typescript support

### PR DESCRIPTION
**Pull request by JasCodes**
Allow correct expansion in typescript.

### CODE REVIEW

**Comment by idleberg** [comment]
> Allow correct expansion in typescript.

Hey, thanks for the support, but I'm not sure what the message above means. Is there anything wrong with the [existing support](https://github.com/idleberg/vscode-emoji-code/blob/0.7.0/package.json#L71-L74) for TypeScript?

**Comment by JasCodes** [comment]
Hey @idleberg 
In my vscode typescript context was expanding to hexadecimal format 0x000000.

Thx

**Comment by idleberg** [comment]
Can you please provide an example? Also, if that was true, I don't see how your PR would fix it. The content of `emoji-javascript.json` and `emoji-typescript.json` would be identical.

**Comment by JasCodes** [comment]
Oh, I didn't even tried in js 😝; assumed it kinna worked.

Here wat i am getting
screenshot_2018-07-14 01 46 55_mqxtsq
screenshot_2018-07-14 01 47 00_xj33ep

Thx

**Comment by idleberg** [comment]
I think the problem was caused by `vsce` and should be fixed in v0.7.2

**Comment by JasCodes** [comment]
Oh cool!!

**Pull request closed without merging**
