### PR TITLE
Add C#

### PR DESCRIPTION
**Pull request by kamranayub**
Adds C# support

### CODE REVIEW

**Review by idleberg — CHANGES_REQUESTED** [review]
Please stick to existing whitespace settings

**Comment by kamranayub** [comment]
Must be Git/VS Code, I'll fix it.

**Comment by kamranayub** [comment]
Fixed? GH doesn't let me remove the newline at the end...

**Comment by idleberg** [comment]
Looks good to me. Will merge this later today. Thank you!

**Comment by kamranayub** [comment]
Thank you for an awesome extension! 🥇

**Pull request merged**
